/** Account and category names extracted from financePM.json. */

export const Accounts = [
  "Card PB Sasha",
  "Card PB Sasha Digital",
  "Card MB Sasha",
  "Cash Sasha",
  "Cash Other",
  "PE PB Sasha USD",
  "PE PB Sasha EUR",
  "Cash USD",
  "Cash EUR",
  "Cash Katya",
  "Card PB Katya",
  "Card Aval Katya",
  "Card UkrSib Katya",
  "PE UkrSib Katya USD",
  "Dd",
  "Kkk",
  "Xxx",
  "Cash Sasha",
  "Card Sasha Alfabank ",
  "Card Sasha Privatbank",
  "Cash Katya",
  "Cash other",
  "Cash EUR",
  "Cash USD",
  "Cash UAH Other",
  "Card AB Sasha",
  "Deposit PBS USD",
  "Bank EUR",
  "PE PB Sasha UAH",
  "Card PB Katya",
  "Card PB Sasha Pay",
  "Monobank",
  "Cash GEL",
  "Deposit PBK USD",
  "Депозити",
  "Hgg",
  "Пак",
  "Wize",
  "Binance",
  "Card PB Sasha Pay",
  "Card PB Sasha On",
  "Card Star",
  "Card USD",
  "Inter",
] as const;

export const Categories = [
  "Auto",
  "Clothes",
  "Credit",
  "Education",
  "Entertainment",
  "Family",
  "Food",
  "Friends",
  "Health & Beauty",
  "Home",
  "Other",
  "Taxes/fees",
  "Gift",
  "Other",
  "Salary",
  "Auto insurance",
  "Car service",
  "Gas",
  "Eating out",
  "Groceries",
  "Medical care",
  "SPA",
  "Sport",
  "Cleaning services",
  "Electronics",
  "Furniture",
  "Sale",
  "Food",
  "Transport",
  "Entertainment ",
  "Car",
  "Other",
  "Taxes",
  "Phone",
  "Public",
  "Taxi",
  "Cinema",
  "Theatre",
  "Restaurant",
  "Gift",
  "Other",
  "Home",
  "Services",
  "Work",
  "Household goods",
  "Health",
  "Health",
  "Clothes",
  "Beauty ",
  "Traveling",
  "Education",
  "Bank service",
  "Flat Lutsk",
  "Bike",
  "111",
  "Helpers",
  "Sport",
  "Out of report",
  "Other",
  "Home Renovation 2019",
  "Tips",
  "Work",
  "Copenhagen ",
  "Bukovel 2020 feb",
  "ЖК Sky Avenue",
  "Nova poshta",
  "ЖК Respublica",
  "Parking ",
  "Hobby",
  "2021",
  "Egypt",
  "Rhodes",
  "Wedding ",
  "ЖК Рідний Дім",
  "Буковель жовтень",
  "PE",
  "2020",
  "2019",
  "2018",
  "Italy",
  "Europe 22.12",
  "Greece ",
  "Georgia ",
  "Belgium",
  "Карпати",
  "Wroclaw ",
  "Львів 15.02",
  "Turkey",
  "Istanbul ",
  "Barcelona",
  " Bukovel",
  "Thailand",
  "Bukovel Feb",
  "Iceland",
  "Malta",
  "Черче 03",
  "Bukovel oct",
  "Taxes deposit",
  "Буковель грудень",
  "Cell",
  "Taxes",
  "ЖК Старт",
  "Meet with friends",
  "Бензин",
  "Покупка квартири",
  "Donations ",
  "Subscribe",
  "2022",
  "Буковель Серпень",
  "Мийка",
  "Cafe ",
  "Квартира",
  "Комунальні ",
  "Ремонт",
  "Інше ",
  "Комунальні",
  "2023",
  "Португалія",
  "Продаж",
  "Books",
  "Ремонт",
  "Паркінг",
  "Квартира",
  "Комунальні",
  "Вольво",
  "Переїзд",
  "Вро",
  "Оренда Р1",
  "Комуналка",
  "2025",
  "Буковель січень",
  "ЖК Respublica 2",
  "Квартира",
  "Life needs",
  "Комунальні",
  "Ремонт",
  "Буковель червень",
  "Оренда Р2",
  "Мадейра",
  "Оренда Атлантік",
  "Переїзд",
  "Т",
  "Комунальні",
  "Т",
  "Оренда",
  "Буковель вересень",
  "Оренда О",
  "Оренда",
  "Освіти, 14а",
  "Комунальні",
  "ЖК Республіка 3",
  "Квартира",
  "Inzhur",
  "2026",
  "Буковель, лютий",
  "Буковель, квітень",
] as const;
